version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: cmd/main.go
    goos:
      - linux
      - darwin

archives:
  - format: binary
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
